### ISSUE TITLE
Crash after the newest update

### ISSUE THREAD

**Issue by sirben99** [segabl/pd2-streamlined-heisting#10]
Hey!

I experienced a weird crash that i havent seen before when i updated.
I was playing on hoxton breakout day 2, and when the assault started the seacond time and the HRT units came the game just crashed. They came from the roof that they blow up to the server room. I hope this gives some info!
Juding by crashlog something happened with Iter, which happened to also update yeasterday (Somewhere this week atleast). It also mentioned Better Assault Indicator, but im not sure if thats reveland.

Crashlog:
[crash.txt](https://github.com/segabl/pd2-streamlined-heisting/files/6988473/crash.txt)

BLT Log:
[2021_08_15_log.txt](https://github.com/segabl/pd2-streamlined-heisting/files/6988479/2021_08_15_log.txt)

If i should report this somewhere else instead, please let me know!

Side note: Should i report these issues here or on ur mod page? Just asking for a preferred place.

EDIT: It happened again. Same crash as above. Seems to be on every heist going loud, stealth is fine.

Ben

**Comment by segabl** [comment]
That could be a mod conflict with Iter, though I am using that too, albeit with the pathing improvement option disabled currently.
Could you turn off that option and see if that fixes it?

Reporting on github is preferred since it's easier for me to keep track of issues

**Comment by segabl** [comment]
Should hopefully be fixed with c5561e74ad80edccc65f42ef19346c97409761b2

**Comment by sirben99** [comment]
Hey!

I desided to comment a follow up to the fix, woke up and tested it, everything works fine!

Do you sugsect leaving Iters Impoved Pathing disabled or enabled?

Ben

**Comment by segabl** [comment]
Should be fine with it enabled, I had it enabled before but disabled it for some testing, then forgot to enable it again, that's why I didn't catch that error.

**Comment by sirben99** [comment]
Hey!

Ah, got it. It seems to work fine now with it enabled, thank you for the fix! If any more issues come up ill report them to the github!

Side note 2: Would it be possible to make the "enemy shoot while in animations" fix a standalone mod? My friend stopped playing payday 2 because of that bug, since sniper could one shot him even tho they were in an animation. Hes fine with more gameplay changhing mods but i think people would enjoy it. 

I no means mean to push you to make some of ur features from this mod or any other as standalones and i hope you dont take it that way! I just thought it would be intresting to see the fixes to the base game (Like the enemy animation shooting) as a standalone fix mod, since this is the only mod that fixes those kinds of bugs, but also changes gameplay. But it might be a bit unnessasery

Anyway, i dont mean to necro this thread, since its getting off topic on my part. Thank you for the fix once again!

Ben

**Comment by segabl** [comment]
Most fixes should be simple enough to make standalone, I've documented every function I changed/wrote so it's up to others to port fixes they want without playing with the mod itself.
