### ISSUE TITLE
Enabling Medic fire panic animations

### ISSUE THREAD

**Issue by sirben99** [segabl/pd2-streamlined-heisting#11]
Hey!

I noticed for a long time that medics dont have a fire panic animation like all the other units (Expect Bulldozer, Shields and Cloaker). I saw a mod on the workshop that enables them and though would it be possible to implement in this mod, if it fits the scope?

Ben

**Comment by segabl** [comment]
I think that's connected to not having any hurt animations on the medic, which is mostly done so the animations don't bug out when they try to heal during that.

**Comment by sirben99** [comment]
Hmm, i dint think of that. I assume that enabling hurt/fire animations on medic would cause issues with healing animations then?

**Comment by segabl** [comment]
Without adding additional checks to medic healing, yeah. and the system is kinda weird since the cop that wants the heal picks the medic and not vice versa

**Comment by sirben99** [comment]
Huh, dint know that, i thought medic would pick the cop.

Anyway, if you want to look into how it would be possible to implement without breaking stuff i think it add little extra to the mod! But by the sounds of it it may be better to leave as it is.

Sorry for the late response, i had a bit of a rough day XD

You can close this issue if you see fit. Thank you for reading my sugsection!

**Comment by segabl** [comment]
I'll keep it in mind

**Comment by sirben99** [comment]
Sounds good!

On a bit of a unrelated note, do you know is there a place where i could make a mod sugsection?

I would like to have Sociopaths Overdog each concecutive melee hit damage buff timer more than 1 seacond. I play with many custom melee weapons with randomizer, and many of the weapons cant possibly hit the mark since theyr too slow, which makes the melee build kinda pointless. Many vanilla weapons also have this issue, so it would be preferably 3 seaconds instead. I tried to make it my self but i for the life of me coudnt get it to work XD.

Sorry again for asking a very off topic question. Please say if you want me to stay in this mods topic only to be more consistant!

**Comment by segabl** [comment]
there's a dedicated mod request channel on the mws discord server, though for your particular case, I think the card description is wrong, I recently started making a complementary skill tweaks mod for streamlined heisting and looking over those decks to see where they need changes I found the actual duration is 7 seconds

**Comment by sirben99** [comment]
The duration increase is in Infiltrator perk deck, Advanced Close Combat, since that buffs Overdog to 7 seaconds.
Sociopath doesent have this do it says in flat 1

Source: https://payday.fandom.com/wiki/Perk_Decks

This is also noticable ingame with huds that show perk deck buffs, and ingame is very noticable that its 1 seacond

**Comment by segabl** [comment]
Oh right, checked again, it's a separate upgrade in the code. Well, I guess I will add that to my other mod then

**Comment by sirben99** [comment]
Awesome!

Do you know how compatible ur Streamlined Heisting Compliments is with other overhaul mods to skills etc?

Im mainly talking about these two, since im using them currently:
https://modworkshop.net/mod/32323
https://modworkshop.net/mod/21561

I like the changes that ur mod does to the skills, but i would also like to have Freas Overhaul since it moves some skills around which makes builds abit more flexable for my taste. I noticed that they both mess with drill timer perks, so i would assume theyr not 100% combatible.

Should i join the MWS discord server and ask if someone could make the Sociopatch timer change a standalone mod?

Thank you for ur time and all ur help with these questions! I hope im not being a nuisance with them.

**Comment by segabl** [comment]
Ace of aces would probably not work but idk, try it out. I'm sure someone on the MWS discord can help you out.
