### ISSUE TITLE
Stealth Detection going up more consistently

### ISSUE THREAD

**Issue by sirben99** [segabl/pd2-streamlined-heisting#12]
Hey!

I was wondering could it be possible to  make it so stealth detection would go up and down more consistently? What i mean by this is that currently the stealth detection goes up by 2-4%, which is pretty inconsistant on how much the meter fills up. Could it be possible to smooth this out so the detection isnt so drastic?

Im not sure do you plan to update the stealth section with this mod, but i think it would benefit to have a streamlined stealth experience also, it being a bit harder with some new bells and whistles based on difficulty. 
If you prefer to only update the loud section of the game thats fine too, and i wont make any more stealth related suggsections!

Side question: Do you also plan to touch Crime Spree at same point? Currently i like to play crime spree without some modifications (Like all forced, captain shiels, heavy sniper) since they bring down the enjoyment. The forced experially make it un-fun, since it forces you to quit at a sertain point, or abuse some systems like EMC rush while wasting hundreds of coins to get that one perfect heist.
Imo its a great idea of having random heist given to you and thown in some modifiers to make it more intresting, but its implemented very poorly from an enjoyment standpoint, and there are little to none mods that could make some changes other than mods that change the whole game.

Thank you for your time!

Ben

**Comment by segabl** [comment]
I don't really plan on changing stealth, and increasing the detection frequency might have unintended side effects that I'm not aware of (might detect smoother but faster). The same kind of applies to crime spree, there's not a lot to change there imo and all you really need to be able to play it properly is the crime spree fixes mod.

**Comment by sirben99** [comment]
Yeah i undrestand. Stealth is fine as it is even in base game, and the crime spree stuff is more of a personal prefrence.
I wont be making suggsections on those two things then!

Thank you for listening my suggsection! You can close this issue now if you want.
