### ISSUE TITLE
Some heavies have incorrect body armour

### ISSUE THREAD

**Issue by erushinj** [segabl/pd2-streamlined-heisting#17]
Body armour on unit `units/pd2_dlc_bph/characters/ene_murkywater_heavy_shotgun/ene_murkywater_heavy_shotgun` still protects the backside

Discovered when porting the model to vanilla for [Streamlined Murkies](https://modworkshop.net/mod/41727)

**Comment by erushinj** [comment]
Zombie SWAT heavies also lack body armour

**Comment by segabl** [comment]
Thanks, regarding Zombies not gonna bother for now since they haven't been touched at all yet but once I do I will make sure to include the changes made to regular swat for zombies too

**Comment by erushinj** [comment]
Murky heavy shotgunner fixed
Zombie heavy SWAT covered by #20 

Closing issue
