### ISSUE TITLE
Wrong units spawning on Death Sentence

### ISSUE THREAD

**Issue by erushinj** [segabl/pd2-streamlined-heisting#21]
Russian faction (with faction tweaks disabled) and zombie faction (always) use SWAT-tier units on Death Sentence

**Comment by segabl** [comment]
Coming back to this, considering there is no DS tier for mercs and the MH/DW tier is fugly, I'd rather have them use SWAT tier. Is there any other issue with that other than technically being a lower tier faction?
Zombie faction kinda falls under #20

**Comment by erushinj** [comment]
Heavies in that tier for either faction lack body armour

It's not a major issue by any means, but it does go against the "all heavies have body armour" thing the rest of the factions (and Russians when the host has faction tweaks enabled) have

**Comment by segabl** [comment]
ah right then it's just a matter of ensuring I always use armored heavies, regardless of faction tweaks

**Comment by erushinj** [comment]
Just remembered about this

Any additional thoughts now that unit categories have been cleaned up, or should this be closed ?

**Comment by segabl** [comment]
Ah right, this is resolved now as part of 07bfe73f8c9656818b6fec62053495038428d581 so closing it as completed
