### ISSUE TITLE
Some Russian NPC weapons are silent

### ISSUE THREAD

**Issue by erushinj** [segabl/pd2-streamlined-heisting#23]
AS VAL, AKMSU, SR2, and RPK for NPCs are all silent when firing

Checked for mods touching the NPC AS VAL, none but SH do

**Comment by erushinj** [comment]
Also believe the NPC Mosconi is affected which is..weird

**Comment by segabl** [comment]
Russian ones prob need their unit files updated with the proper soundbank dependencies if they don't already have them. Note however that weapon sound swaps behave weirdly on custom maps, for isntance mosconi is silent on all custom maps but works fine on vanilla heists. There's some weirdness involved in how beardlib loads dependencies I guess.

**Comment by erushinj** [comment]
Checked the Russian weapons even on Boiling Point, they still seemed to be silent

**Comment by segabl** [comment]
Then they probably need their sound dependencies updated. Might aswell switch these from xml tweaks to unit overrides and see if that fixes it for custom maps, not like other mods would really touch npc weapon unit files anyways.
