### ISSUE TITLE
Scarface Mansion guards sound like cops

### ISSUE THREAD

**Issue by erushinj** [segabl/pd2-streamlined-heisting#25]
Noticed by Medicat

Took a look, seems like the speech prefixes for `bolivian` and `bolivian_indoors` aren't changed from vanilla in charactertweakdata

**Comment by segabl** [comment]
Had a look at this and as expected, none of the gangster voice lines are loaded on the heist. Even if loaded manually they lack a lot of the common sounds for stealth related stuff so they would mostly be mute, so there's no good solution to this.
