### ISSUE TITLE
Mission Script: Flashlights don't work

### ISSUE THREAD

**Issue by Hater-mater** [segabl/pd2-streamlined-heisting#26]
I wanted to report issue with flashlights when they don't work on client but recently tested No Mercy in SH and both host and client don't have flashlights. Our perspective on screenshots below:
![image](https://github.com/segabl/pd2-streamlined-heisting/assets/78091338/16e75952-1ac5-43f8-8457-46f21cbb527a)

![image](https://github.com/segabl/pd2-streamlined-heisting/assets/78091338/bdd84b00-bfbf-4be3-810e-fcd3da7b0649)

**Comment by segabl** [comment]
The flashlight mission patches are intended to be used with another mod that enables the flashlights on all NPC weapons and not just shields, without that mod you wouldn't notice a difference. I think it's no longer online so I may look into implementing that feature into Streamlined Heisting itself.

**Comment by Hater-mater** [comment]
I thought "More NPC flashlights" mod is not required. Sorry then

Also add in `missionmanager.lua` "client_on_executed" hook otherwise `set_flashlights_on()` is not executing on client

**Comment by segabl** [comment]
> Also add in `missionmanager.lua` "client_on_executed" hook otherwise `set_flashlights_on()` is not executing on client

client_on_executed runs on_executed for the selected elements so it should work fine without a specific hook to that

**Comment by Hater-mater** [comment]
I didn't saw flashlights on shield units so :shrug:
