### ISSUE TITLE
Crime Spree: Big Bank Escape Doesn't Trigger

### ISSUE THREAD

**Issue by Chaoxufurwa** [segabl/pd2-streamlined-heisting#27]
I found that only in the Crime Spree mode, the escape doesn't trigger after collecting the 4 mandatory loot bags for the Big Bank heist. The escape plan in preplanning seems to have no real effect on the issue either. I've tried the default roof escape and the Elevator Trick and neither had the escape trigger. 
The Plan B option doesn't change whether it triggers either. Neither using the Beast to open the vault or thermite to drop into the vault allowed the escape to trigger.

I lost the screenshot I had, so I'll see if I can update this once I have both a screenshot and a brief recording of the issue happening.

**Comment by segabl** [comment]
I have noticed this before but I haven't had the time to check if this is an issue only in Streamlined Heisting (which I don't really think it is as it would happen on the regular Big Bank aswell)

**Comment by Chaoxufurwa** [comment]
I looked around and saw a mod that claimed to just be the part of Streamlined Heisting that allows extra loot bags to count for points during a crime spree, and it had issues with the exact same thing happening. 

Pretty sure that's the root cause of it, because after disabling Streamlined Heisting (which only changed that one thing in Crime Spree mode) Big Bank worked completely fine in Crime Spree again.

**Comment by segabl** [comment]
Huh, interesting, I'll have a look, not sure how this would cause that issue.

**Comment by segabl** [comment]
Should now be fixed
