### ISSUE TITLE
Panic Room: Doors remain close and mess with AI Pathing

### ISSUE THREAD

**Issue by Chaoxufurwa** [segabl/pd2-streamlined-heisting#28]
I'm not sure how consistent of an issue this is on the dev-branch, but I ran into this last night.

[Screenshot](https://imgur.com/a/khq2Uam)
First of all, the cops came right away, which is probably just fixing a longstanding bug with PAYDAY 2 in general here, but the problems come after. Doors that should be open or potentially get opened by gangsters remained shut.

Seems innocent enough, apart from locking off some of the loot on the map. But then I noticed some of my bot companions were having a hard time pathfinding. They would get stuck defending a location, without me having told them to hold position or to defend an area.

**Comment by segabl** [comment]
Do you happen to  be using Alarmingly Streamlined Spawngrups? That mod had some bigger changes to Panic Room very recently tthat involved closing off some doors, so that might be the actual culprit there.

**Comment by Chaoxufurwa** [comment]
Oh, I didn't even think that could be the problem. Yes. I do have that installed. I'll see what they're able to come up with.
