### ISSUE TITLE
Autofire_rounds crash

### ISSUE THREAD

**Issue by Ravenous212** [segabl/pd2-streamlined-heisting#4]
[crash.txt](https://github.com/segabl/pd2-streamlined-heisting/files/5746098/crash.txt)
Not certain if it's just a random crash or related to "The Fixes", seeing as I was able to run about 3 maps before this and nothing broke... however, the last map was "Proving Grounds" on death sentence instead of mayhem/death wish... though I doubt that had much to do with it.

**Comment by segabl** [comment]
Hmm, you got any other mods that change enemies somehow? can you search your mods for ``autofire_rounds``? The crash suggests that in some preset one falloff entry contains ``autofire_rounds`` while another one doesn't, which shouldn't really happen if presets aren't modified by another mod.

**Comment by Ravenous212** [comment]
Dumbass me forgot to remove Less BS OD, whoops...

**Comment by segabl** [comment]
Anyways, it shouldn't happen anymore as I added an additional check in the latest update
