### ISSUE TITLE
Fps loss with Streamlined Heisting installed

### ISSUE THREAD

**Issue by sirben99** [segabl/pd2-streamlined-heisting#6]
Hey!

I desided to see what makes my fps dip when doing heist loud, and saw that removing Streamlined heisting seemed to help with it. I dont recall having these issues from the start, so maybe some update to the mod causes it. I dint expect a smooth as butter running game with this huge of a mod installed, but i thought maybe something could be improved fps wice. If this is normal and you cant do anything about it, please let me know!

I tested on a first world bank and my results are:

With Streamlined Heisting:
Average: 80-70
Min: 60

Without Streamlined Heisting:
Average: 100
Min: 90

It seems to have about 30 fps difference on average.

Graphic settings: Everything on lowest possible expect Texture Quality, wich is set to high.

Computer specs:
Nvidia GeForce RTX 2070 SUPER
AMD Ryzen 5 3600 6-Core Processor, 12 CPUs, 3.6Hz
16GB Ram

I remeber that Think Faster caused huge fps loss because it increased cop think rate, and i recall seeing something simelar in ur patch notes about specials being marked as important so theyr tasks could be used for full potential.

I hope this somehow narrows it down what the issue is, if you need more testing/help let me know and ill try to profide more useful info!

Ben

EDIT: Hmm, after wiping my mod_overrides folder, i saw that the numbers changed a bit

With Stream:
Average: 90-80
Min: 80

Without:
Average: 100-90
Min: 90-80

It seems like something in there is messing up the fps with Streamlined. Im now going to remove all the mods, and only leave streamlined in to see what happens.

EDIT 2: Now tested without any other mods expect Streamlined and Hoplib, and fps loss maybe 5 fps. So in conclusion:

Streamlined doesent accually drop the fps on its own, but removing it when other mods are installed does make the game run better, as seen in the first test. This is intresting. Going to test what mods now drop it.

EDIT 3: Okay ive been at this for about an hour or two and i really cant put my finger on what is causing the lag and what is possibly effecting Streamlined Heisting. Im going to leave this open incase you want to read it, but feel free to close it since i really dont know anymore.

**Comment by segabl** [comment]
The noticable drops are possibly cause by the increased task limit, they shouldn't be this severe though so I don't know what other mod would cause the increased drop you're experiencing. Maybe you can share your mod list?

**Comment by sirben99** [comment]
Hey!

Sorry for the extreme late responce. Ive been trying to solve my fps problem when the assault starts, but i have no idea what could cause it. I noticed that deleting Tweakdatafixed, The Fixes and Project Deadlocked helped to keep it atleast in the 100:ish fps most of the time, but its still very unstable.

I dont have streamlined installed since im testing in general without it, but heres the modlist (I installed The Fixes back just so i can profide the modlist, so please ignore it.There are also some questonable mods in there, but i use them for purelly entertainment, and not for unlocking achievments, public lobbies etc)

[The Fixes Info.txt](https://github.com/segabl/pd2-streamlined-heisting/files/6492966/The.Fixes.Info.txt)

There is my modlist (And yes i have over 550 mod_overrides mods, but theyr the easyest to trouble shoot in binary search)

Know if any of these mods cause any problems? (Wolfhud is the forked version, not the original)

Ben

**Comment by segabl** [comment]
Hm, I'm not seeing anything problematic here, at least nothing that would lower FPS specifically in combination with Streamlined Heisting.

**Comment by sirben99** [comment]
I deleted some more mods and it seem to have stabiliced more now, i will have to do more testing tho

**Comment by segabl** [comment]
let me know if you find out which mod causes it, then I can have a look at it and see why

**Comment by sirben99** [comment]
Well, supricingly i made some progress on my normal fps issues. When removing Bot weapons And Equipment and Useful bots mods, the fps never dipped below 100. When those two were installed, it would randomly dip as low as 70 sometimes. Very weird

**Comment by segabl** [comment]
No worries. If there's any potential incompatibility it's good to try and see if it can be fixed. However as you say, it just seems kind of random in your case. The game does hickup every now and then and adding mods on top can make it more noticable. Anyway, the higher your general fps the more you'll see it dip every now and then in my experience.
