### ISSUE TITLE
HRT and Asssault Break improvments

### ISSUE THREAD

**Issue by sirben99** [segabl/pd2-streamlined-heisting#7]
Hey!

I would like to sugsect some improvments to HRT and Assault Breaks.

HRT: Im not sure how this would work, but i was wondering if HRT would have more of an impact during assault breaks. I really like the idea of HRT, but they dont seem that unique, just another cop to shoot at that shoots back. Im not sure how it currently works, but would it be possible to edit enemy hostage rescue priority, so enemies during Assault (Escpecially when theres player and hostage close progsimity of each other) would have lower/none task to rescue the hostages, but the opposite would be true to the HRT. This does sound a bit silly that a armed officer woudnt rescue/try to rescue hostages, but i think it would benefit HRT abit. I would like to think HRT as more of a special enemy than an accual normal SWAT unit, maybe adjust theyr spawns during assault breaks etc. I dont know how they work at all in the mod/in the base game code (If they have any special code other than just disabling them). 

Assault Breaks: I noticed that the assaults have been sligthly longered in the patch notes. Sorry if im wrong about this and this is already a feature, i dint pay that much attention how long the breaks last, but ive noticed that the HRT (Atleast a couple of versions ago) seemed to just come and go, even disapear right in front of my eyes, possibly because the assault breaks are so short. A counter to slightly longer assaults would be slightly longer assault breaks, that would scale with difficulty and hostage amount. E.g: Normal mode would have the longest assault break, and having hostages would make it even longer, while One Down would have the shortest and having hostages slightly longers it, but not too much. This would benefit the game emphetizing having hostages even more, and would go hand in hand with the upper HRT changes.

These are my ideas how the breaks would be more intresting during assault down time. I would like to hear ur side of this, and what and what would not be possible to implement, or if you want to implement at all!

Ben

**Comment by segabl** [comment]
Thank you for your suggestions. I have thought about changing the behaviour of enemies rescuing hostages before. I'm not sure how possible it is to lower the priority of them doing it, the easiest thing is to either allow it or don't allow it at all, which I don't really want to do. HRT is specifically spawned by the game to rescue hostages and take bags so they should be doing that if there are any around. It is true that on bigger maps it takes them too long to reach their objective and they are told to retreat once the assault begins again. There's not really a way around it other than making assault breaks last super long which isn't ideal. Assault breaks already scale with difficulty and with hostage amount, the shortest assault break you can get (which is on DS) with the maximum amount of hostages is 40 seconds, which is already double the amount that you can get in vanilla. I could lower the hostage requirement for that though, currently you need 8 hostages to get the maximum assault delay.

**Comment by sirben99** [comment]
Hey!

Thank you for listening to my suggsections and giving some insight on how things work! 

HRT: Disabling other enemy hostage rescue isnt the ideal solution, but if the priority system somehow would work i think that would be the best solution. But if you can find any other way than disabling rescue all together, leaving as it is would be for the best, since it takes away a whole game mechanic.

Assault Breaks: I guess i never noticed that the assault breaks are longer, i ususally play on overkill since ive already done all one down stuff, and it seemed almost the same as vanilla. Although i usually dont guard hostages, so that might be the problem. Do dominated cops count to this hostage reguerment? If they do, i think the max dom is about 5? And since on some maps theres no civs or its impossible to get 8 to get the full assault break time.

Ben

**Comment by segabl** [comment]
Dominated cops count for this yes. Which is why I'm thinking I should lower the scaling such that you can get the maximum effect even on heists without hostages.

**Comment by sirben99** [comment]
That sounds good in my books! This would also make the mod mechanic more accessable in every heist, wich imo is a good thing.

**Comment by segabl** [comment]
Lower hostage requirement has now been added in the dev branch of the mod (b99afa4) and will be included in the next update when there are enough changes to warrant an update.
