### ISSUE TITLE
Disable enemies checking for corpses and broken objects outside of stealth

### ISSUE THREAD

**Issue by sirben99** [segabl/pd2-streamlined-heisting#8]
Hey!

I noticed that in Think Faster changelog (https://modworkshop.net/mod/29403#changelog), enemies no longer dont check for corpses and broken object outside of stealth, which in return gives an noticable fps boost.
I was wondering could this also be applied to this mod, or would it be more of an idea stealing/not something that would go with what this mod does. This could help with the fps issues i noticed in earlyer discussion when going loud (I think i managed to sort most of them out/gotten used to it).

I dont know if Think Faster is compatable with this mod, since this mod changes some of the enemies thinking speed (Like specials), so i thought id ask if this could be possible to implement to this mod, or be ported to a standalone mod, since it seems to be a base game issue. (Ik this is for Streamlined Heisting issues, but id thought id ask for possibility of a standalone mod so i dont spam you in modworkshop for example. Please let me know where i should contact you if i had an standalone mod idea! I thought this would be more conviniant in this instance)

Whats your thoughts on this?

Ben

**Comment by segabl** [comment]
I was working on something like this but stopped since at that point I was aware of at least 2 mods that already do it with a potentially 3rd upcoming one and it seemed reduant to implement it. Think faster should be compatible, I don't see any conflicts there, all it really does is allowing to configure the cop task limit.

**Comment by sirben99** [comment]
Hey!

Thank you for your answer! Imo it would be wort it to implement it (to the mod or as stand), since i think it would benefit everyone that uses it, but maybe as a "when i have time" or low priority. But if you think its still reduntant to do i respect ur desission!

Do you recall what the other 2 mods were that did this, besides Think Faster?

Ben

**Comment by segabl** [comment]
The other one would be FSS (Full Speed Swarm) and the 3rd one isn't released yet as far as I'm aware.

**Comment by sirben99** [comment]
Ah, i had to drop FFS since i had some compability issues i think (Something dint work right atleast). I might give a Think Faster a go. Theoreticly, if i set the think rate to 60 (base game), i could use it only as a fps booster?

**Comment by segabl** [comment]
In theory, yes (though streamlined heisting uses an increased tickrate of 90). However, in practice I haven't noticed any FPS increases using it. But you can give it a try and see if it helps.

**Comment by sirben99** [comment]
Ill test it soon if it helps with fps. I should propably change the rate to 90, since ur mod uses that value

**Comment by sirben99** [comment]
Nice! I already did a edit on groupaistatebase, in which i took Streamlined heistings version, and copyed Think Fasters checks to disable those things in it. Im not sure if it accually is working, but i gave it a shot just incase.

Thank you for coming back to this! Take ur time with it, like you sayd its not a high priority, and i undrestand that it will take time to make further improvments.
