### ISSUE TITLE
Crimespree crash

### ISSUE THREAD

**Issue by tamadNaBrowNie** [segabl/pd2-streamlined-heisting#9]
The game consistently crashes during a crimespree. It runs for a few minutes then it crashes. I have to check if it consistently around the same amount of time. Here are the crashlogs. They happen with the mod installed.
[crash.txt](https://github.com/segabl/pd2-streamlined-heisting/files/6759326/crash.txt)

[crashlog.txt](https://github.com/segabl/pd2-streamlined-heisting/files/6759325/crashlog.txt)

**Comment by segabl** [comment]
what level of crimespree and which modifiers? Personally I haven't had any issue like that.

**Comment by segabl** [comment]
gonna assume this is a missing HopLib issue. if not, feel free to reopen
